services:
  web:
    container_name: uw-coursemap-web
    image: ghcr.io/twangodev/uw-coursemap-web:latest
    build:
      context: .
    env_file: ".env"
    restart: unless-stopped
    ports:
      - "3000:3000"
