name: Bug report
description: File a bug report to help us improve the project
labels: ["bug", "triage"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: dropdown
  id: target
  attributes:
    label: Where did this happen?
    description: "Select the target where you encountered the bug."
    options:
      - "Website (Svelte)"
      - "Search Endpoint"
      - "API Endpoint"
    default: 0
  validations:
    required: true
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: "Also tell us what you expected to happen."
    placeholder: |
      Tell us what you see!
  validations:
    required: true
- type: input
  id: platform
  attributes:
    label: Platform
    description: "What platform/Browser are you using?"
    placeholder: "Browser (Chrome, Firefox, Safari, etc), or your Operating System (if not web related)"
  validations:
    required: true