/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all subject codes and names */
        get: operations["getSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all term codes and names */
        get: operations["getTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get last update timestamp */
        get: operations["getUpdate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API manifest */
        get: operations["getManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get course by ID */
        get: operations["getCourseCourseid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/{courseId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get course meetings */
        get: operations["getCourseCourseidMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructors/{instructorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get instructor by ID */
        get: operations["getInstructorsInstructorid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instructors/{instructorId}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get instructor meetings */
        get: operations["getInstructorsInstructoridMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/global_graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get global prerequisite graph */
        get: operations["getGlobal_Graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graphs/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subject prerequisite graph */
        get: operations["getGraphsSubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/graphs/course/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get course prerequisite graph */
        get: operations["getGraphsCourseCourseid"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/global_style": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get global graph style */
        get: operations["getGlobal_Style"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/styles/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subject graph style */
        get: operations["getStylesSubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quick_statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get quick statistics */
        get: operations["getQuick_Statistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats/{subject}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subject statistics */
        get: operations["getStatsSubject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildings/{buildingName}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meetings by building */
        get: operations["getBuildingsBuildingnameMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meetings by date */
        get: operations["getMeetingsDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meetings/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meetings index with date statistics */
        get: operations["getMeetingsIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject}/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meetings by subject */
        get: operations["getSubjectsSubjectMeetings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildings/{buildingName}/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get building meetings for a specific date */
        get: operations["getBuildingsBuildingnameDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * MandatoryAttendance
         * @description Mandatory attendance statistics from RMP.
         */
        MandatoryAttendance: {
            /**
             * Yes
             * @default 0
             */
            yes: number;
            /**
             * No
             * @default 0
             */
            no: number;
            /**
             * Neither
             * @default 0
             */
            neither: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * Rating
         * @description Individual rating from RMP.
         */
        Rating: {
            /** Comment */
            comment: string;
            /** Quality Rating */
            quality_rating: number;
            /** Difficulty Rating */
            difficulty_rating: number;
        };
        /**
         * RatingsDistribution
         * @description Rating distribution from RMP.
         */
        RatingsDistribution: {
            /**
             * R1
             * @default 0
             */
            r1: number;
            /**
             * R2
             * @default 0
             */
            r2: number;
            /**
             * R3
             * @default 0
             */
            r3: number;
            /**
             * R4
             * @default 0
             */
            r4: number;
            /**
             * R5
             * @default 0
             */
            r5: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * RMPData
         * @description Rate My Professors data for an instructor.
         */
        RMPData: {
            /** Id */
            id: string;
            /** Legacy Id */
            legacy_id: number;
            /**
             * Average Rating
             * @default null
             */
            average_rating: number | null;
            /**
             * Average Difficulty
             * @default null
             */
            average_difficulty: number | null;
            /**
             * Num Ratings
             * @default 0
             */
            num_ratings: number;
            /**
             * Would Take Again Percent
             * @default null
             */
            would_take_again_percent: number | null;
            /** @default null */
            mandatory_attendance: components["schemas"]["MandatoryAttendance"] | null;
            /** @default null */
            ratings_distribution: components["schemas"]["RatingsDistribution"] | null;
            /**
             * Ratings
             * @default []
             */
            ratings: components["schemas"]["Rating"][];
        };
        /**
         * CoursePrerequisites
         * @description Prerequisites information for a course.
         */
        CoursePrerequisites: {
            /** Prerequisites Text */
            prerequisites_text: string;
            /** Linked Requisite Text */
            linked_requisite_text: (string | components["schemas"]["CourseReference"])[];
            /** Course References */
            course_references: components["schemas"]["CourseReference"][];
            /**
             * Abstract Syntax Tree
             * @default null
             */
            abstract_syntax_tree: unknown | null;
        };
        /**
         * CourseReference
         * @description Reference to a course by subject codes and number.
         */
        CourseReference: {
            /** Subjects */
            subjects: string[];
            /** Course Number */
            course_number: number;
        };
        /**
         * EnrollmentData
         * @description Enrollment information for a course in a specific term.
         */
        EnrollmentData: {
            /** @default null */
            school: components["schemas"]["School"] | null;
            /**
             * Last Taught Term
             * @default null
             */
            last_taught_term: string | null;
            /**
             * Typically Offered
             * @default null
             */
            typically_offered: string | null;
            /**
             * Credit Count
             * @default [
             *       0,
             *       0
             *     ]
             */
            credit_count: [
                number,
                number
            ];
            /**
             * General Education
             * @default false
             */
            general_education: boolean;
            /**
             * Ethnic Studies
             * @default false
             */
            ethnic_studies: boolean;
            /**
             * Instructors
             * @default {}
             */
            instructors: {
                [key: string]: string | null;
            };
        };
        /**
         * GradeData
         * @description Grade distribution data for a course or instructor.
         */
        GradeData: {
            /** Total */
            total: number;
            /** A */
            a: number;
            /** Ab */
            ab: number;
            /** B */
            b: number;
            /** Bc */
            bc: number;
            /** C */
            c: number;
            /** D */
            d: number;
            /** F */
            f: number;
            /** Satisfactory */
            satisfactory: number;
            /** Unsatisfactory */
            unsatisfactory: number;
            /** Credit */
            credit: number;
            /** No Credit */
            no_credit: number;
            /** Passed */
            passed: number;
            /** Incomplete */
            incomplete: number;
            /** No Work */
            no_work: number;
            /** Not Reported */
            not_reported: number;
            /** Other */
            other: number;
            /**
             * Instructors
             * @default null
             */
            instructors: string[] | null;
        };
        /**
         * School
         * @description School/college information.
         */
        School: {
            /** Name */
            name: string;
            /** Abbreviation */
            abbreviation: string;
            /** Url */
            url: string | null;
        };
        /**
         * TermData
         * @description Data for a specific term including enrollment and grade information.
         */
        TermData: {
            /** @default null */
            enrollment_data: components["schemas"]["EnrollmentData"] | null;
            /** @default null */
            grade_data: components["schemas"]["GradeData"] | null;
        };
        /**
         * Course
         * @description Complete course information.
         */
        Course: {
            course_reference: components["schemas"]["CourseReference"];
            /** Course Title */
            course_title: string;
            /** Description */
            description: string;
            prerequisites: components["schemas"]["CoursePrerequisites"];
            /**
             * Optimized Prerequisites
             * @default null
             */
            optimized_prerequisites: components["schemas"]["CourseReference"][] | null;
            /** @default null */
            cumulative_grade_data: components["schemas"]["GradeData"] | null;
            /** Term Data */
            term_data: {
                [key: string]: components["schemas"]["TermData"];
            };
            /**
             * Similar Courses
             * @default []
             */
            similar_courses: components["schemas"]["CourseReference"][];
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            /** Satisfies */
            satisfies?: components["schemas"]["CourseReference"][];
            /**
             * Has Meetings
             * @default false
             */
            has_meetings: boolean;
        };
        /**
         * FullInstructor
         * @description Complete instructor information including RMP data.
         */
        FullInstructor: {
            /** Name */
            name: string;
            /**
             * Email
             * @default null
             */
            email: string | null;
            /** @default null */
            rmp_data: components["schemas"]["RMPData"] | null;
            /**
             * Position
             * @default null
             */
            position: string | null;
            /**
             * Department
             * @default null
             */
            department: string | null;
            /**
             * Credentials
             * @default null
             */
            credentials: string | null;
            /**
             * Official Name
             * @default null
             */
            official_name: string | null;
            /**
             * Courses Taught
             * @default null
             */
            courses_taught: components["schemas"]["CourseReference"][] | null;
            /** @default null */
            cumulative_grade_data: components["schemas"]["GradeData"] | null;
        };
        /**
         * MeetingLocation
         * @description Physical location for a class meeting.
         */
        MeetingLocation: {
            /** Building */
            building: string | null;
            /** Room */
            room: string | null;
            /**
             * Coordinates
             * @default null
             */
            coordinates: [
                number,
                number
            ] | null;
            /**
             * Capacity
             * @default null
             */
            capacity: number | null;
        };
        /**
         * Meeting
         * @description A class meeting/section.
         */
        Meeting: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Start Time */
            start_time: number | null;
            /** End Time */
            end_time: number | null;
            /** @default null */
            location: components["schemas"]["MeetingLocation"] | null;
            /**
             * Current Enrollment
             * @default null
             */
            current_enrollment: number | null;
            /**
             * Instructors
             * @default []
             */
            instructors: string[];
            /**
             * Course Reference
             * @default null
             */
            course_reference: unknown | null;
        };
        /**
         * Leaf
         * @description A leaf node in the requirement AST - either text or a course reference.
         */
        Leaf: {
            /** Payload */
            payload: string | unknown;
        };
        /**
         * Node
         * @description A node in the requirement AST with an operator and children.
         */
        Node: {
            /** Operator */
            operator: string;
            /** Children */
            children: (components["schemas"]["Node"] | components["schemas"]["Leaf"])[];
        };
        /**
         * RequirementAbstractSyntaxTree
         * @description The root of a requirement AST.
         */
        RequirementAbstractSyntaxTree: {
            /** Root */
            root: components["schemas"]["Node"] | components["schemas"]["Leaf"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all subject codes and names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getTerms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get all term codes and names */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get last update timestamp */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        updated_on?: string;
                    };
                };
            };
        };
    };
    getManifest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lists all available resources for discovery */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        subjects?: string[];
                        courses?: string[];
                        instructors?: string[];
                        /** Format: date-time */
                        updated_on?: string;
                    };
                };
            };
        };
    };
    getCourseCourseid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Course identifier (e.g., COMPSCI_200)
                 * @example COMPSCI_200
                 */
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get course by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCourseCourseidMeetings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course identifier */
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get course meetings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInstructorsInstructorid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Instructor identifier (sanitized name)
                 * @example JOHN_DOE
                 */
                instructorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get instructor by ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FullInstructor"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInstructorsInstructoridMeetings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Instructor identifier */
                instructorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get instructor meetings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGlobal_Graph: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get global prerequisite graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    getGraphsSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Subject code
                 * @example COMPSCI
                 */
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get subject prerequisite graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            id?: string;
                            source?: string;
                            target?: string;
                            parent?: string;
                        };
                    }[];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGraphsCourseCourseid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Course identifier */
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get course prerequisite graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGlobal_Style: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get global graph style */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
        };
    };
    getStylesSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subject code */
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get subject graph style */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getQuick_Statistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get quick statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total_courses?: number;
                        total_instructors?: number;
                        total_ratings?: number;
                        total_detected_requisites?: number;
                        total_grades_given?: components["schemas"]["GradeData"];
                    };
                };
            };
        };
    };
    getStatsSubject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subject code */
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get subject statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        total_courses?: number;
                        total_detected_requisites?: number;
                        total_grades_given?: components["schemas"]["GradeData"];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBuildingsBuildingnameMeetings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Building name */
                buildingName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get meetings by building */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMeetingsDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Date in MM-DD-YY format
                 * @example 01-15-25
                 */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get meetings by date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMeetingsIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get meetings index with date statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: {
                            total_buildings?: number;
                            total_meetings?: number;
                            total_instructors?: number;
                            total_students?: number;
                        };
                    };
                };
            };
        };
    };
    getSubjectsSubjectMeetings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subject code */
                subject: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get meetings by subject */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBuildingsBuildingnameDate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Building name */
                buildingName: string;
                /** @description Date in MM-DD-YY format */
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get building meetings for a specific date */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meeting"][];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
