name: Node.js CI

on:
  push:
  pull_request:

env:
  PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL }}
  PUBLIC_SEARCH_API_URL: ${{ vars.PUBLIC_SEARCH_API_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
