name: Python Linting

on:
  push:
  pull_request:

jobs:
  ruff:
    name: Ruff Linting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [generation, search]
    defaults:
      run:
        working-directory: ./${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      
      - name: Install Dependencies
        run: uv sync --dev
      
      - name: Run Ruff Format Check
        run: uv run ruff format --check .
      
      - name: Run Ruff Linter
        run: uv run ruff check .